# Generated by Django 3.1.1 on 2020-09-16 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('engine', '0030_auto_20200914_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('rating', models.FloatField(default=5.0)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('submitted', 'SUBMITTED'), ('rejected', 'REJECTED')], max_length=16)),
                ('estimated_quality', models.FloatField(default=5.0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('annotator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examination_set', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.job')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('frame', models.PositiveIntegerField()),
                ('significant', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('message', models.CharField(default='', max_length=4096)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.job')),
                ('labeled_shape', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.labeledshape')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tracked_shape', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.trackedshape')),
            ],
        ),
    ]
